security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        database:
            entity:
                class: App\Infrastructure\Doctrine\Entity\User
                property: username
    encoders:
        App\Infrastructure\Doctrine\Entity\User:
            algorithm: bcrypt
            cost: 12
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout: ~
            form_login:
                login_path: login
                check_path: login
            guard:
                authenticators:
                    - App\Auth\GithubGuardAuthenticator
