sudo: required
services:
    - docker

before_script:
    - docker-compose pull
    - docker-compose build
    - docker-compose create
    - docker-compose start
    - docker-compose ps
    - curl --silent --show-error https://getcomposer.org/installer | php
    - php composer.phar install
    - docker-compose run php ./bin/build.sh

script:
    - docker-compose run -w /project php ./vendor/bin/phpunit
    - docker-compose run -w /project php ./vendor/bin/behat
