language: php

php:
  - 7.2

sudo: required
services:
    - docker

before_script:
    - docker-compose pull
    - docker-compose build
    - docker-compose create
    - docker-compose start
    - docker-compose ps
    - cp .env.travis env
    - composer install
    - env ENV=test docker-compose run php ./bin/build.sh

script:
    - docker-compose run -w /project php ./vendor/bin/phpunit
    - docker-compose run -w /project php ./vendor/bin/behat
