php:
    build: .
    volumes: 
        - .:/project
    links:
        - elasticsearch
        - mysql

web:
    image: nginx:latest
    ports: 
        - "80:80"
    volumes: 
        - .:/project
        - ./docker/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

mysql:
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
        - "3307:3306"

elasticsearch:
    image: elasticsearch:latest
    environment: []
    ports:
        - "9201:9200"

