web:
    image: nginx:latest
    ports: 
        - "8080:80"
    volumes: 
        - .:/project
        - ./docker/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes: 
        - .:/project
    links:
        - elasticsearch

elasticsearch:
    image: elasticsearch:latest
    environment: []
    ports:
        - "9201:9200"
