php:
    build: .
    volumes: 
        - .:/project
    links:
        - elasticsearch
        - mysql

web:
    image: nginx:latest
    volumes: 
        - .:/project
        - ./docker/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

mysql:
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: root

elasticsearch:
    image: elasticsearch:latest
    environment: []

