parameters:
    github_client_id: 1234 
    github_client_secret: 1234
    archive_path: '%kernel.root_dir%/../../tests/Workspace/archive'

services:
    _defaults:
        public: true

    App\Infrastructure\Doctrine\Repository\DoctrineUserRepository:
        public: true
        autowire: true

doctrine:
    dbal:
        url: mysql://root:root@mysql:3306/phpbench_reports_test
